# Generated by Django 5.1.1 on 2024-09-12 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StationStatus',
            fields=[
                ('station_id', models.UUIDField(primary_key=True, serialize=False)),
                ('is_installed', models.IntegerField()),
                ('is_renting', models.IntegerField()),
                ('is_returning', models.IntegerField()),
                ('num_bikes_available', models.IntegerField()),
                ('num_bikes_disabled', models.IntegerField()),
                ('num_ebikes_available', models.IntegerField()),
                ('num_docks_available', models.IntegerField()),
                ('num_docks_disabled', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SystemRegions',
            fields=[
                ('region_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StationInformation',
            fields=[
                ('station_id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('capacity', models.IntegerField()),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citibike.systemregions')),
            ],
        ),
    ]
