# Generated by Django 5.1.1 on 2024-09-12 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citibike', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationinformation',
            name='region_id',
            field=models.ForeignKey(db_column='region_id', on_delete=django.db.models.deletion.CASCADE, to='citibike.systemregions'),
        ),
    ]
